# Generated by Django 3.1 on 2023-04-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userCoding',
            fields=[
                ('user_code', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('salary', models.CharField(max_length=100)),
            ],
        ),
    ]
