# Generated by Django 3.1 on 2023-04-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20230425_0411'),
        ('userCoding', '0002_auto_20230425_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoding',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
    ]
