# Generated by Django 3.1 on 2023-04-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20230424_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
